[DEFAULT]
bottom_to_top = yes
use_cm = no
case_per_column = 12

[PXL]
left_margin = 47
right_margin = 30
left_column_width = 758
right_column_width = 758
top_margin = 200
bottom_margin = 140

[CM_A4]
left_margin = 0.4
right_margin = 0.6
left_column_width = 9.4
right_column_width = 9.4
top_margin = 3
bottom_margin = 2.7